//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektPrototypeProgram.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjektPrototypeProgram.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unbelievable, wrong and “virtually impossible.”
        ///That was how President Donald Trump’s administration responded Monday to the Congressional Budget Office’s politically damaging score of House Republicans’ plan to repeal and replace Obamacare.
        ///The nonpartisan CBO projected that the bill, the American Health Care Act, would insure 24 million fewer Americans than Obamacare by 2026 but reduce the federal deficit by $337 billion in the same span.
        ///“We disagree strenuously with the report that was put out,” Heal [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string health_care_report_bogus {
            get {
                return ResourceManager.GetString("health_care_report_bogus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No victim has come forward. There&apos;s no investigation. And physical evidence? That doesn&apos;t exist either.
        ///But thousands of people are convinced that a paedophilia ring involving people at the highest levels of the Democratic Party is operating out of a Washington pizza restaurant.
        ///The story riveted fringes of Twitter - nearly a million messages were sent last month using the term &quot;pizzagate&quot;.
        ///One man even travelled hundreds of miles to the restaurant with a gun and opened fire, claiming he was there to &quot;se [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Pizzagate1 {
            get {
                return ResourceManager.GetString("Pizzagate1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US police have arrested a man wielding an assault rifle who entered a pizza restaurant that was the target of fake news reports it was operating a child abuse ring led by Democratic presidential candidate Hillary Clinton and her top campaign aide.
        ///An unidentified 35-year-old man was being held for questioning after police were called to the Comet Ping Pong restaurant in Washington near the Maryland border, said Aquita Brown, a spokeswoman for the Metropolitan Police Department in the nation’s capital.
        ///Fak [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Pizzagate2 {
            get {
                return ResourceManager.GetString("Pizzagate2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to President Donald Trump should be taken literally and seriously, but only “if he&apos;s not joking,” White House press secretary Sean Spicer explained Monday.
        ///
        ///Spicer did not say how to tell what is and isn&apos;t a joke.
        ///
        ///
        ///During a daily briefing in which he tried to parse, interpret and explain several of Trump&apos;s recent tweets and statements, Spicer at first evaded a reporter&apos;s question—perhaps the central question facing the new administration—about whether the public can trust what the president says, given h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Public_can_trust_Trumps_words {
            get {
                return ResourceManager.GetString("Public_can_trust_Trumps_words", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In February 2017, English-language web sites caught wind of a “suicide game” that had reportedly resulted in more than a hundred deaths in Russia.
        ///The general premise of the game, which goes by several names but is commonly referred to as the “blue whale” game, is as follows:
        ///The player signs up to play the game and agrees to follow instructions over the course of 50 days.
        ///An administrator assigns a series of tasks (anything from cutting yourself to listening to song) that the player must accomplish. 
        ///T [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RussianSuicideGame {
            get {
                return ResourceManager.GetString("RussianSuicideGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The population of Denmark is less than the population of Germany..
        /// </summary>
        internal static string tekst1 {
            get {
                return ResourceManager.GetString("tekst1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The population of Denmark is greather than the population of Germany. .
        /// </summary>
        internal static string tekst2 {
            get {
                return ResourceManager.GetString("tekst2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to President Donald Trump pledged to forego a presidential salary, but as his second payday approaches, the White House is declining to say if the president has donated any of his earnings yet.
        ///During the campaign, Trump promised he would take &quot;no salary&quot; if elected — a pledge he reiterated after he won.
        ///&quot;I&apos;m not going to the take the salary,&quot; he told &quot;60 Minutes&quot; in November.
        ///The Constitution, however, requires that the president receive a salary, and that it not be reduced during his term. 
        ///Federal law m [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Trump_Salary {
            get {
                return ResourceManager.GetString("Trump_Salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A federal judge in Hawaii has blocked President Donald Trump&apos;s new travel ban, hours before it was due to begin after midnight on Thursday.
        ///US District Judge Derrick Watson cited &quot;questionable evidence&quot; in the government&apos;s argument that the ban was a matter of national security.
        ///President Trump described the ruling as &quot;unprecedented judicial overreach&quot;.
        ///The order would have placed a 90-day ban on people from six mainly Muslim nations and a 120-day ban on refugees.
        ///Mr Trump insists the move is to stop te [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Trump_travel_ban_BBC {
            get {
                return ResourceManager.GetString("Trump_travel_ban_BBC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A federal judge in Hawaii issued a nationwide order Wednesday evening blocking President Trump’s ban on travel from parts of the Muslim world, dealing a stinging blow to the White House and signaling that Mr. Trump will have to account in court for his heated rhetoric about Islam.
        ///
        ///The ruling was the second major setback for Mr. Trump in his pursuit of a policy he has trumpeted as critical for national security. His first attempt to sharply limit travel from a handful of predominantly Muslim countries end [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Trump_travel_ban_NYT {
            get {
                return ResourceManager.GetString("Trump_travel_ban_NYT", resourceCulture);
            }
        }
    }
}
